server:
  port: 8080
  servlet:
    context-path: /challenge-api
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true